const data ={
    coursesdata:[
        {
            id:1,
            img:'https://th.bing.com/th/id/R.16ad62472fc0888656831d949a14dee5?rik=o4y1xpi49FwdTw&pid=ImgRaw&r=0',
            name:'Design',
            img1:'https://www.daymarcollege.edu/sites/default/files/graphic-design-courses.jpg',
            title1:'Jump Start your Career Graphic',
            img2:'https://th.bing.com/th/id/R.76d34328224bb5fbf192867bd113aace?rik=%2bt5unTboIurxcg&riu=http%3a%2f%2fwww.hamstech.com%2fblog%2fwp-content%2fuploads%2f2017%2f06%2finterior-designing-course1.jpg&ehk=vRVg6bw96T4ZLseSdLEZY16tsZ5PcAEMd1fFBKSMTPA%3d&risl=&pid=ImgRaw&r=0',
            title2:'Hamstechms Interior Designing Weekend',
            img3:'https://th.bing.com/th/id/OIP.bLABkqcZtR0L-nyv0LhO1AAAAA?pid=ImgDet&w=300&h=200&rs=1',
            title3:'Art mA|SUNY Oswego Academic Progame',
            img4:'https://th.bing.com/th/id/OIP.gRv1-3NW8E7-0MwvYQ6a4AAAAA?pid=ImgDet&w=395&h=266&rs=1',
            title4:'Transportation Center Overview | Beaver Works',
            img5:'https://northsidetools.com/wp-content/uploads/2020/11/interpretation-team-500x251.jpg',
            title5:'Advanced Production Logging Service and Tools ...',
            img6:'https://th.bing.com/th/id/R.8ccf8938078d6dfb822588947327dd2f?rik=oH274Y9Hd9rh9w&riu=http%3a%2f%2fonline.brescia.edu%2fwp-content%2fuploads%2f626x313-blogpost-GDcourses-BRES.jpg&ehk=fvSrMk%2bsAwvQWTkpDnBbGIEA5Is6RZRW0VDuIpnopao%3d&risl=&pid=ImgRaw&r=0',
            title6:'Graphic Design Courses You Will Takw for Your Degree',
            img7:'https://th.bing.com/th/id/OIP.Fq1iRy_AiIZWgx2UmhTe5QHaEK?pid=ImgDet&rs=1',
            title7:'Web Design and Graphic Design Courses | Web Designer Classes',
            dec:'Design Courses'
        },
        {
            id:2,
            img:'https://th.bing.com/th/id/R.7b92192a54197dd4b3b40de1cadc7cae?rik=FDYlolk0jCOdYw&pid=ImgRaw&r=0',
            name:'Devolpment',
            img1:'https://elysiumacademy.org/wp-content/uploads/2016/02/Web-Development.jpg',
            title1:'Web Development Training Course | Elysium Academy',
            img2:'https://infinityblogger.com/wp-content/uploads/2021/01/4884785-scaled.jpg',
            title2:'Best web development courses',
            img3:'https://th.bing.com/th/id/R.bef5e38ca32930c799473cb7937e80ab?rik=rH%2fpCWtFVQBcJA&riu=http%3a%2f%2fwww.icollegete.com%2fwp-content%2fuploads%2f2019%2f02%2fbanner-03-1-1-1.jpg&ehk=Y%2fWqg8jpoyEOlZ0QZjzgMuZ1Q5TCDW6ig0FTrBx%2ffDQ%3d&risl=&pid=ImgRaw&r=0',
            title3:'Web Development Course In Rawalpindi, Pakistan - Icollegete',
            img4:'https://th.bing.com/th/id/R.1b777bc05b489f7d66487aad1e2bc925?rik=V6TyTju7aM8N1A&riu=http%3a%2f%2fplutomultimediainstitute.in%2fwp-content%2fuploads%2f2015%2f08%2fCourses-Inner-Page-03.png&ehk=fDLkReZsRdGq8QEwCWY5UJ2h%2fZyxSRXceiPjnF0bjcA%3d&risl=&pid=ImgRaw&r=0',
            title4:'Web Development Courses Baroda & Website Development ...',
            img5:'https://www.aptechnoida.com/images/course/full/web-development-training.jpg',
            title5:'Best Web Development Training Institute in Noida : Aptech ...',
            img6:'https://th.bing.com/th/id/R.e697447bdd8b9388d0be2ec4b3954e51?rik=aCuxNFk4gKLHpQ&riu=http%3a%2f%2fcdn.iphonehacks.com%2fwp-content%2fuploads%2f2015%2f12%2fthe-complete-web-developer-course.jpg&ehk=A3ISz6zo2jYCD94ztwcKEmlVCYaRmvRU5RXCTnly4RU%3d&risl=&pid=ImgRaw&r=0',
            title6:'Learn to be a Web developer with the Udemy Web Developer ...',
            img7:'https://mikkegoes.com/wp-content/uploads/2018/03/The-best-web-development-courses-for-beginners-Start-learning-web-development-and-coding-online-480x784.jpg',
            title7:'Best Web Design Course Training in Pro Creations Web ...',
            dec:'Devolpment Courses'  
        },
        {
            id:3,
            img:'https://th.bing.com/th/id/OIP.ZVvYHHWBhLG_0M8pdDC44wHaEK?w=287&h=180&c=7&r=0&o=5&pid=1.7',
            name:'Marketing', 
            img1:'https://th.bing.com/th/id/OIP.IFRGFnozSYTKZPnpJH0dMAHaDP?pid=ImgDet&rs=1',
            title1:'Marketing Courses - E-Classroom',
            img2:'https://th.bing.com/th/id/OIP.Z6f_6MJDHQ8GuM0ZROMdRgHaEj?pid=ImgDet&rs=1',
            title2:'Marketing training in Chandigarh with JOB Assurance',
            img3:'https://marketingartfully.com/wp-content/uploads/2015/05/marketing-mini-courses-1024x512.png',
            title3:'Marketing Courses | Marketing Artfully',
            img4:'https://5.imimg.com/data5/QB/QF/MY-40326254/digital-marketing-training-class-500x500.jpg',
            title4:'Digital Marketing Training Class in Ameerpet, Hyderabad ...',
            img5:'https://th.bing.com/th/id/OIP.5biDiCoQmakjx9wwm6YhcAHaEy?pid=ImgDet&rs=1',
            title5:'MBA Marketing Courses, Scope and Career in Pakistan',
            img6:'https://th.bing.com/th/id/OIF.eL9eoXxpka5EGDSr997BWw?pid=ImgDet&rs=1',
            title6:'Tricks To Achieve Best Results By Digital Marketing ...',
            img7:'https://www.techstack.in/blog/wp-content/uploads/2021/11/Digital-Marketing-Training-1024x576.jpg',
            title7:'Importance of Taking Best Digital Marketing Training ...',
            dec:'Marketing Courses'   
        },
        {
            id:4,
            img:'https://www.embien.com/images/main_content/embedded-software-development.jpg',
            name:'Software', 
            img1:'https://gulfjobvacancy.com/wp-content/uploads/2015/12/training.jpg',
            title1:'Software Engineer',
            img2:'https://blog.commlabindia.com/wp-content/uploads/2019/06/microlearning-software-training.jpg',
            title2:'Microlearning for Software Training: 5 Reasons You Shouldn ...',
            img3:'https://blog.commlabindia.com/wp-content/uploads/2015/01/Overcome-Software-Training-Challenges-Using-eLearning-Solutions.png',
            title3:'3 Tips to Design Effective Software Training Courses - An ..',
            img4:'https://th.bing.com/th?id=OIF.mFVN8G1WXSDw0Vwy%2blNLhw&pid=ImgDet&rs=1',
            title4:'Software-Devolper-Course',
            img5:'https://th.bing.com/th/id/OIF.gdNwlrWlwkZAkiSMySviFg?pid=ImgDet&rs=1',
            title5:'Software Testing Course in Nashik | SevenMentor',
            img6:'https://vle.estio.co.uk/estio/images/sofware-image.jpg',
            title6:'Software Apprenticeships with Estio Training',
            img7:'https://pxl-yorksjacuk.terminalfour.net/1600x1000/smart/prod01/yorksjacuk/media/content-assets/2019-courses/software-engineering-hero.jpg',
            title7:'Software Engineering BSc (Hons) | York St John University',
            dec:'SoftWare Courses'
        },
        {
            id:5,
            img:'https://th.bing.com/th/id/R.7a6d15d34f1a7358ad543adc62d4735e?rik=twkMGfs1jf%2b9jg&pid=ImgRaw&r=0',
            name:'Photography', 
            img1:'https://th.bing.com/th/id/OIP.IFRGFnozSYTKZPnpJH0dMAHaDP?pid=ImgDet&rs=1',
            title1:'Marketing Courses - E-Classroom',
            img2:'https://th.bing.com/th/id/OIP.Z6f_6MJDHQ8GuM0ZROMdRgHaEj?pid=ImgDet&rs=1',
            title2:'Marketing training in Chandigarh with JOB Assurance',
            img3:'https://marketingartfully.com/wp-content/uploads/2015/05/marketing-mini-courses-1024x512.png',
            title3:'Marketing Courses | Marketing Artfully',
            img4:'https://5.imimg.com/data5/QB/QF/MY-40326254/digital-marketing-training-class-500x500.jpg',
            title4:'Digital Marketing Training Class in Ameerpet, Hyderabad ...',
            img5:'https://th.bing.com/th/id/OIP.5biDiCoQmakjx9wwm6YhcAHaEy?pid=ImgDet&rs=1',
            title5:'MBA Marketing Courses, Scope and Career in Pakistan',
            img6:'https://th.bing.com/th/id/OIF.eL9eoXxpka5EGDSr997BWw?pid=ImgDet&rs=1',
            title6:'Tricks To Achieve Best Results By Digital Marketing ...',
            img7:'https://www.techstack.in/blog/wp-content/uploads/2021/11/Digital-Marketing-Training-1024x576.jpg',
            title7:'Importance of Taking Best Digital Marketing Training ...',
            dec:'Marketing Courses'
        },
        {
            id:6,
            img:'https://th.bing.com/th/id/R.bf7afd264820c21de95ef7ede348b037?rik=k%2fTzDI80R0258g&pid=ImgRaw&r=0',
            name:'Personal Devolpment', 
            img1:'https://th.bing.com/th/id/OIP.v7d4DtCLtwLPHc70oOA1SQHaE8?pid=ImgDet&rs=1',
            title1:'ShapingtheOdds - #ShapingtheBlogs -Personal Devolpment Cousrses ',
            img2:'https://th.bing.com/th/id/R.36d88ac1395117de89af2a25226768bb?rik=SG4fAl%2bRY4Gj0w&riu=http%3a%2f%2fpitmantrainingscotland.co.uk%2ftraining%2fwp-content%2fuploads%2f2014%2f02%2fPersonal-Development-424x282.jpg&ehk=75Anzx%2bBZgJLSjiTAHS9Oeu4NS3gLuNoLYmGxDN8S5g%3d&risl=&pid=ImgRaw&r=0',
            title2:'Personal Development Courses from Pitman Training Scotland',
            img3:'https://th.bing.com/th/id/R.c3fc3843044b11a1695266e0b9ad2a09?rik=g2tIbJS5gJY6JQ&pid=ImgRaw&r=0',
            title3:'Your Personal Development Online Training just £10.00',
            img4:'https://www.freshpd.com/wp-content/uploads/persoanl-development.png',
            title4:'Personal Development Courses | freshpd',
            img5:'https://th.bing.com/th/id/R.9948f87130fd85a8f8ec1e07040f3343?rik=EfqRpiR2hYfCCg&pid=ImgRaw&r=0',
            title5:'Personal Development Plan Course Materials | Free Training',
            img6:'https://th.bing.com/th?id=OIF.RbuNh%2bxDFlBdXRBrJv67zA&pid=ImgDet&rs=1',
            title6:'Best Personal Development Courses - selfprogress.net',
            img7:'https://selfprogress.net/wp-content/uploads/2021/11/pexels-photo-52608-768x513.jpeg',
            title7:'Best Personal Development Courses - selfprogress.net',
            dec:'Personal Devolpment Courses'
        },
        {
            id:7,
            img:'https://th.bing.com/th/id/OIP.JQ-Gjwou9ft0LvVBLYVZBQHaE8?pid=ImgDet&rs=1',
            name:'Business', 
            img1:'https://th.bing.com/th/id/R.2fa46550099127120309540afeec6ea7?rik=aG9etfs8ym2krg&riu=http%3a%2f%2fcdn8.openculture.com%2fwp-content%2fuploads%2f2013%2f06%2fbusiness-free-online-course-photo1.jpg&ehk=9eOp9hq8107wRzr7WLtFzKVJCrc%2f%2bo6m0Zg4RDFjQts%3d&risl=&pid=ImgRaw&r=0',
            title1:'Free Business Courses ',
            img2:'https://th.bing.com/th/id/R.789d4970972f9f5633b81f3d4e6a8e32?rik=ycSh4aKQ8RqFGA&riu=http%3a%2f%2fwww.embercarriers.com%2fblog%2fwp-content%2fuploads%2f2013%2f06%2fBusiness-seminar.jpg&ehk=iLaQiFYVyFRk%2f4YazW76bCJKrYvedsq31F7%2fHmHsVVk%3d&risl=&pid=ImgRaw&r=0',
            title2:'Training | Ember Carriers Blog',
            img3:'https://th.bing.com/th/id/OIP.dx4iTCT7MnPBVY0XqzSwfgHaE8?pid=ImgDet&rs=1',
            title3:'Business Courses - IT Training & Certification in Kuwait ...',
            img4:'https://online-learning.harvard.edu/sites/default/files/styles/social_share/public/topics/laptop_FB_size.png?itok=9d-dICxG',
            title4:'Online Business Intelligence Courses | Harvard University',
            img5:'https://th.bing.com/th/id/R.393df0e3f22d3f6ff3c40e3b47caa497?rik=FbEpnWfhPRCqCg&riu=http%3a%2f%2fgenevasbe.com%2fwp-content%2fuploads%2f2015%2f07%2fbusiness-admin.jpg&ehk=L0QRmYP4euuEXzJWTEeMfYi%2bSd8uBFe1f%2bgRrD2FU9c%3d&risl=&pid=ImgRaw&r=0',
            title5:'online business courses',
            img6:'https://th.bing.com/th/id/R.58588d120b2282ba700345de87124ad8?rik=9de0njGibUx4zg&riu=http%3a%2f%2fthepeakperformancecenter.com%2fwp-content%2fuploads%2f2014%2f07%2fBusiness-Training.jpg&ehk=RL6yGeqfdP7kpzC41dLF1fR48M2GhuJZAJqit7wP210%3d&risl=&pid=ImgRaw&r=0',
            title6:'Business training - knowledge, skills, and competencies',
            img7:'https://learnenglish20.com/wp-content/uploads/2018/03/Professional-Courses-Working-In-London-750x430.jpg',
            title7:'The Benefits Of Short Professional Courses Working In ...',
            dec:'Business Courses'
        },
        {
            id:8,
            img:'https://th.bing.com/th/id/OIF.og3IflhFMJRahaCf2xPdKw?pid=ImgDet&rs=1',
            name:'Music', 
            img1:'https://www.stjohnsfrome.co.uk/media/content/images/Photos/B27I6578.jpg',
            title1:'Music lessons ',
            img2:'https://www.gsmd.ac.uk/fileadmin/_processed_/csm_JG_How_to_apply_Music_Header_3712d48edc.jpg',
            title2:'Music Course | Guildhall School of Music & Drama',
            img3:'https://www.moneycrashers.com/wp-content/uploads/2018/12/private-music-lessons-1068x713.jpg',
            title3:'Music Lessons For Kids & Adults - 9 Ways to Save Money',
            img4:'https://leverageedu.com/blog/wp-content/uploads/2021/11/Music-Courses-in-UK.jpg',
            title4:'Music Courses in UK | Study Music in UK | Leverage Edu',
            img5:'https://www.yourspacemusiclessons.com/sites/yourspacemusiclessons.com/files/pictures/1599-your_space_music-29.5.1510585.jpg',
            title5:'Demo Online Music Lessons | Your Space Music Lessons',
            img6:'https://th.bing.com/th/id/R.ee087ac3522f91d628809be3d0dd2f5b?rik=qHAT5T7hQ0TwwA&riu=http%3a%2f%2fwww.amimusic.org%2fwp-content%2fuploads%2f2015%2f08%2fpiano-lesson-1.jpg&ehk=QOZ1BzRJZ%2bgIEo%2btUxmyFEwfcO0iuiutxYheGkABhGQ%3d&risl=&pid=ImgRaw&r=0',
            title6:'Register for Music Lessons',
            img7:'https://images.squarespace-cdn.com/content/v1/603becb6b81d5532a0a66cbb/1636898158618-3AATNYNBFKL9TASLNYUK/unsplash-image-NIJuEQw0RKg.jpg?format=500w',
            title7:'Music Courses Online',
            dec:'Music Courses'
 
        },
        {
            id:9,
            img:'https://www.bgsu.edu/content/dam/BGSU/academics/computer-science/AdobeStock-294794307.jpeg',
            name:'Data Scince', 
            img1:'https://imgshare.io/images/2020/06/29/Best-Data-Science-Courses---Made-with-PosterMyWall.jpg',
            title1:'Best Data Science Courses - ImgShare.io ',
            img2:'https://www.meritglobaltraining.com/images/data1.png',
            title2:'Data Science Courses - Merit Global Training',
            img3:'https://static1.shine.com/l/m/images/blog/Data_science_courses_to_Pursue_during_Lockdown.jpg',
            title3:'Science Courses to Pursue',
            img4:'https://th.bing.com/th/id/R.70b2ef24b597f71a75e3cf0ce4648c8a?rik=I1SmT3eZKSltoQ&pid=ImgRaw&r=0',
            title4:'Data Science Courses - All You Need to Know',
            img5:'https://content.techgig.com/thumb/msid-75487476,width-860,resizemode-4/4-Data-Science-courses-that-are-free-during-Covid-19-lockdown.jpg?99914',
            title5:'4 Data Science courses that are free during Covid-19 ...',
            img6:'https://cdn.guru99.com/images/1/DataScience.png',
            title6:'Best Data Science Courses in 2021',
            img7:'https://www.cursor.tue.nl/fileadmin/_processed_/0/7/csm_data_science_go_7138a369d9.jpg',
            title7:'Data science courses',
            dec:'Data science courses'
        },
        {
            id:10,
            img:'https://assets.siccode.com/i-n-b/naics-code-334111-electronic-computer-manufacturing.jpg',
            name:'IT', 
            img1:'https://www.thetrainingroom.com/getattachment/b5407cb1-3290-434b-a272-aebe28278c56/2017-03-21-IT-courses-1.jpgaspx?lang=en-GB&width=840&height=439&ext=.jpg',
            title1:'IT Courses Online From The Training Room. ',
            img2:'https://i.ytimg.com/vi/-aTIX3Du2mg/maxresdefault.jpg',
            title2:'IT Training for Beginners ',
            img3:'https://th.bing.com/th/id/R.0371f1dc8e0fc28cc8475d7ddd2aa6db?rik=XFu0ah9KXell9A&riu=http%3a%2f%2fwww.aiming.in%2fwp-content%2fuploads%2f2017%2f06%2fIT-Training-Details.jpg&ehk=U%2fwdifbTVVgowcYulf573Je4rSSeNvHfaNu%2bdIlsfrk%3d&risl=&pid=ImgRaw&r=0',
            title3:'IT Training Details - Eligibility, Duration',
            img4:'https://www.kent.ac.uk/itservices/images/training/students.jpg',
            title4:'IT Training for staff and students - Information Services',
            img5:'https://cdn.dnaindia.com/sites/default/files/styles/full/public/2018/09/05/726641-online-coursethinkstockphotos.jpg',
            title5:'IT online course',
            img6:'https://www.exitcertified.com/assets/ContentBuilderImages/c47136f09d/AdobeStock_198397410__ScaleMaxWidthWzMwNDhd.jpg-d93z2j.jpg',
            title6:'ExitCertified: Authorized IT Training and Certifications',
            img7:'https://www.softlogicsys.in/wp-content/uploads/2019/03/corporate-training.jpg',
            title7:'Corporate Training in Chennai | Best Corporate IT Training',
            dec:'IT courses'
        },
        {
            id:11,
            img:'https://th.bing.com/th/id/OIP.6tB1R8UASuZtz_I8C9E31AHaFj?w=229&h=180&c=7&r=0&o=5&pid=1.7',
            name:'Progrming Languages', 
            img1:'https://monkfox.com/wp-content/uploads/2019/03/maxresdefault-8-2-1024x768.png',
            title1:'Php Cours',
            img2:'https://th.bing.com/th/id/OIP.8ueQ2P3QhxRUDxilKlDkjwHaDt?w=251&h=127&c=7&r=0&o=5&pid=1.7',
            title2:'paython cours ',
            img3:'https://th.bing.com/th/id/OIP.OMZrhT3lQHfGE7urPMiPUQHaJ4?w=140&h=187&c=7&r=0&o=5&pid=1.7',
            title3:'C# cours',
            img4:'https://th.bing.com/th/id/OIP._kqCIaycCp4P0SCjb0KbQgHaE8?pid=ImgDet&rs=1',
            title4:'C++ cours',
            img5:'https://th.bing.com/th/id/OIP.-I5cwtp_wWHGu1ilP3xeHgHaFj?w=211&h=180&c=7&r=0&o=5&pid=1.7',
            title5:'Java Cours',
            img6:'https://th.bing.com/th/id/OIP.-6zixkpABSFY8gleHGUyEwHaGi?w=183&h=180&c=7&r=0&o=5&pid=1.7',
            title6:'Swift Cours',
            img7:'https://th.bing.com/th/id/R.99a40c63b5e0f0112feedd516c4da23c?rik=PA0bWzOsow2M1A&pid=ImgRaw&r=0',
            title7:'Java Script Cours',
            dec:'Progrming Languages courses'
        },
        {
            id:12,
            img:'https://th.bing.com/th/id/R.e1deab12d191e168d0320a3e21731c9c?rik=8juajCsg95Ec8w&riu=http%3a%2f%2fmed.stanford.edu%2fcontent%2fdam%2fsm-news%2fimages%2f2018%2f03%2fai-medical-stock.jpg&ehk=kOT9NLOgzFx0rkNDI4b9XZfAiVR7rIgdT%2fpnQl5VO84%3d&risl=&pid=ImgRaw&r=0',
            name:'AI', 
            img1:'https://www.besanttechnologies.com/wp-content/uploads/2018/02/ai-artificial-intelligence-training.jpg',
            title1:'Artificial Intelligence Course in Bangalore',
            img2:'https://360digit.b-cdn.net/uploads/banner/Cert_pg_in_AI_Deep_Learn22.jpg',
            title2:'Artificial Intelligence Course ',
            img3:'https://www.hopetutors.com/wp-content/uploads/2019/06/artificial-intelligence-training-in-chennai.jpg',
            title3:'Artificial Intelligence Training in Chennai',
            img4:'https://huzzaz.com/procoverphotos/artificial-intelligence-course-video.jpg?1592393042',
            title4:'Artificial Intelligence Course Video - I',
            img5:'https://www.inventateq.com/assets/python/artificial_int.jpg',
            title5:'Artificial Intelligence Course in Bangalore',
            img6:'https://th.bing.com/th/id/OIP.fg0egTuqu1jJBfHNFr0YCwHaDu?pid=ImgDet&rs=1',
            title6:'Artificial Intelligence A to Z Specialization Course ...',
            img7:'https://th.bing.com/th/id/OIP.iI8BIxKB0o2wR0_w5YRK_AHaEo?pid=ImgDet&rs=1',
            title7:'Top 5 Artificial Intelligence Courses Online – Sumoscience.com',
            dec:'AI courses'
        }
    ]
}
export default data;
